### ISSUE TITLE
책내 메모리 계층 설명 오타 

### ISSUE THREAD

**Issue by base6666** [wnghdcjfe/csnote#1]
보조기억장치인 HDD, SDD가 모두 휘발성이라고 작성되어있습니다.

**Comment by wnghdcjfe** [comment]
안녕하세요. ㅎㅎ 해당부분 이미 오타 정정처리를 하여 다음쇄때 반영될 예정입니다. 의견 주셔서 감사합니다.

**Comment by base6666** [comment]
넵 알겠습니다. 감사합니다!
