### ISSUE TITLE
109 페이지 수정 사항 제보

### ISSUE THREAD

**Issue by kshired** [wnghdcjfe/csnote#2]
## Description

109 페이지의 **클래스 기반 할당 방식**은 Classful Addressing인데, CIDR ( Classless Inter Domaing Routing ) 으로 잘못 언급되어 있습니다.

## AS-IS

클래스 기반 할당 방식(CIDR)

## TO-BE

클래스 기반 할당 방식(Classful Addressing)

**Comment by wnghdcjfe** [comment]
엇.. 이게 왜 이렇게... ㅎㅎ 찾아주셔서 감사합니다. 다음쇄에 반영하겠습니다. :)
